version: "3.6"
services:
  queue:
    image: rabbitmq:3-management
    container_name: queue
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=queue
  worker1:
    build: worker
    image: localhost:5000/worker
    container_name: worker1
    depends_on:
        - queue
  # worker2:
  #   build: worker
  #   container_name: worker2
  #   depends_on:
  #       - queue
  creator:
      build: creator
      container_name: creator
      image: localhost:5000/creator
      depends_on:
        - queue
        - worker1