apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s.yaml
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: creator
  name: creator
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8888
      targetPort: 8888
  selector:
    io.kompose.service: creator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s.yaml
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: creator
  name: creator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: creator
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s.yaml
        kompose.version: 1.23.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: creator
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_PASS
              value: queue
            - name: RABBITMQ_DEFAULT_USER
              value: admin
          image: localhost:5001/creator
          name: creator
          ports:
            - containerPort: 8888
          resources: {}
      restartPolicy: Never
status: {}