apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s.yaml
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbit-queue
  name: rabbit-queue
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5672
      targetPort: 5672
  selector:
    io.kompose.service: rabbit-queue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s.yaml
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbit-queue
  name: rabbit-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rabbit-queue
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s.yaml
        kompose.version: 1.23.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: rabbit-queue
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_PASS
              value: queue
            - name: RABBITMQ_DEFAULT_USER
              value: admin
          image: rabbitmq:3.8-management
          name: rabbit-queue
          ports:
            - containerPort: 15672
            - containerPort: 5672
          resources: {}
      restartPolicy: Always
status: {}